# version: "3.8"

services:
  trading_bot:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./logs
        target: /shared_logs
      - type: bind
        source: ./trading_logs
        target: /app/trading_logs
    environment:
      - SHARED_LOG_DIR=/shared_logs
      - INSTANCE_LOG_DIR=/app/trading_logs
      - ALPACA_API_KEY=$"PK4HGNHDEMG6JRA0SDHU"
      - ALPACA_SECRET_KEY=$"2xghjJbvOxUxGBKNUJJYxYako2bEFjIt8Gv9Dpdd"
      - ALPACA_BASE_URL=$"https://paper-api.alpaca.markets/v2"

    tty: true
    stdin_open: true
    command: /bin/bash
