version: "3.8"

services:
  trading_bot:
    build: .
    volumes:
      - shared_logs:/shared_logs
      - ./trading_logs:/app/trading_logs
    environment:
      - SHARED_LOG_DIR=/shared_logs
      - INSTANCE_LOG_DIR=/app/trading_logs
      # Add your Alpaca API keys here
      - ALPACA_API_KEY=${ALPACA_API_KEY}
      - ALPACA_SECRET_KEY=${ALPACA_SECRET_KEY}
      - ALPACA_BASE_URL=${ALPACA_BASE_URL}

volumes:
  shared_logs:
    name: finrl_shared_logs
